name: news
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_avif: ^3.0.0
  cupertino_icons: ^1.0.8
  skeletonizer: ^2.1.0+1
  dio: ^5.9.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/

  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
